services:
  spring:
    container_name: spring
    tty: true
    image: maven:3.9.9-amazoncorretto-21
    command: mvn spring-boot:run
    working_dir: /app-root/
    ports:
      - "8080:8080"
    environment:
      RESOURCE_DIR: ./static
      JAVA_OPTS: "-Xdebug -Xrunjdwp:server=y,transport=dt_socket,suspend=n"
      SPRING_THYMELEAF_CACHE: false
    volumes:
      - ./:/app-root/
