services:
  eft-application:
    image: ghcr.io/puzzle/unilu-pruefungsabfrage:${TAG:-latest}
    container_name: unilu-pruefungsabfrage
    hostname: unilu-pruefungsabfrage
    network_mode: host
    environment:
      KS_PW: ${KS_PW}
      KS_TYPE: ${KS_TYPE:-PKCS12}
      KEY_ALIAS: ${KEY_ALIAS:-unilu-eft}
      SEC_LOCATION: ${SEC_LOCATION:-secrets/prod}
    volumes:
      - type: bind
        source: ./${SEC_LOCATION:-secrets/prod}/httpd.keystore.p12
        target: /${SEC_LOCATION:-secrets/prod}/httpd.keystore.p12
        read_only: true
      - type: bind
        source: ${RESOURCE_LOCATION}
        target: /resources
        read_only: true

  shibboleth-service-provider:
    image: ghcr.io/puzzle/unilu-pruefungsabfrage-shibboleth-sp:${TAG:-latest}
    container_name: unilu-pruefungsabfrage-shibboleth-sp
    hostname: unilu-pruefungsabfrage-shibboleth-sp
    network_mode: host
    environment:
      LOG_LEVEL: warn
    volumes:
      - type: bind
        source: ./${SEC_LOCATION:-secrets/prod}/httpd.crt.pem
        target: /etc/pki/tls/certs/httpd.crt.pem
        read_only: true
      - type: bind
        source: ./${SEC_LOCATION:-secrets/prod}/httpd.key.pem
        target: /etc/pki/tls/private/httpd.key.pem
        read_only: true
      - type: bind
        source: ./${SEC_LOCATION:-secrets/prod}/sp.crt.pem
        target: /etc/shibboleth/sp.crt.pem
        read_only: true
      - type: bind
        source: ./${SEC_LOCATION:-secrets/prod}/sp.key.pem
        target: /etc/shibboleth/sp.key.pem
        read_only: true
      - type: bind
        source: ./secrets/SWITCHaaiRootCA.crt.pem
        target: /etc/shibboleth/SWITCHaaiRootCA.crt.pem
        read_only: true
