include:
  - sp-docker-compose.yml

services:
  eft-application:
    image: ghcr.io/puzzle/unilu-pruefungsabfrage:${TAG:-latest}
    container_name: unilu-pruefungsabfrage
    hostname: unilu-pruefungsabfrage
    network_mode: host
    volumes:
      - type: bind
        source: ./${SEC_LOCATION:-secrets/prod}/httpd.keystore.p12
        target: /${SEC_LOCATION:-secrets/prod}/httpd.keystore.p12
        read_only: true
