#!/usr/bin/env bash

NODE_ENV="$1"
if [[ -z $NODE_ENV ]]; then
  NODE_ENV="test"
  echo "No environment provided, default is $NODE_ENV"
fi

echo "Create httpd certificate for node environment $NODE_ENV"

openssl req -newkey rsa:2048 -nodes -x509 -days 3700 -config resources/$NODE_ENV/httpd.crt.conf -out resources/$NODE_ENV/httpd.crt.pem