#!/usr/bin/env bash

NODE_ENV="$1"
if [[ -z $NODE_ENV ]]; then
  NODE_ENV="test"
  echo "No environment provided, default is $NODE_ENV"
fi

echo "Starting shibboleth-sp for node environment $NODE_ENV using host network..."

docker container run \
    -it \
    --rm \
    --detach \
    --name shibboleth-sp \
    --hostname shibboleth-sp \
    --network=host \
    shibboleth-sp-$NODE_ENV

docker container ls | grep shibboleth-sp