services:
  shibboleth-service-provider:
    image: ghcr.io/puzzle/unilu-pruefungsabfrage-shibboleth-sp:${TAG:-latest}
    container_name: unilu-pruefungsabfrage-shibboleth-sp
    hostname: shibboleth-sp
    network_mode: host
    volumes:
      - type: bind
        source: ./${SEC_LOCATION:-secrets/test}/httpd.crt.pem
        target: /etc/pki/tls/certs/httpd.crt.pem
        read_only: true
      - type: bind
        source: ./${SEC_LOCATION:-secrets/test}/httpd.key.pem
        target: /etc/pki/tls/private/httpd.key.pem
        read_only: true
      - type: bind
        source: ./${SEC_LOCATION:-secrets/test}/sp.crt.pem
        target: /etc/shibboleth/sp.crt.pem
        read_only: true
      - type: bind
        source: ./${SEC_LOCATION:-secrets/test}/sp.key.pem
        target: /etc/shibboleth/sp.key.pem
        read_only: true
      - type: bind
        source: ./secrets/SWITCHaaiRootCA.crt.pem
        target: /etc/shibboleth/SWITCHaaiRootCA.crt.pem
        read_only: true
