server:
  address: edview.unilu.ch
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:certs/prod/httpd.keystore.p12
    key-store-password: uni-lu-eft-2024
    key-alias: unilu-eft
    client-auth: want
  ajp:
    protocol: https
    port: 8448
    packet.size: 65536

logging.level:
  root: info
  ch.puzzle.eft: info
  org.springframework.security: info
  org.apache: info
