server:
  address: edview.unilu.ch
  port: 8443
  forward-headers-strategy: framework
  ssl:
    key-store-type: PKCS12
    key-store: classpath:certs/prod/httpd.keystore.p12
    key-store-password: uni-lu-eft-2024
    key-alias: unilu-eft
    client-auth: want

spring:
  application:
    name: exam-feedback-tool
  security:
    saml2:
      relyingparty:
        registration:
          switch-saml2:
            assertingparty:
              entity-id: https://edview.unilu.ch/idp/shibboleth
              verification:
                credentials:
                  - certificate-location:
                      classpath:certs/prod/httpd.crt.pem
              singlesignon:
                url: https://edview.unilu.ch/Shibboleth.sso/Login
                sign-request: false
              # metadata-uri: classpath:metadata.aaitest+idp.xml
              # metadata-uri: classpath:testxml.xml
              # metadata-uri: classpath:metadata.aaitest+idp.xml
              # metadata-uri: classpath:metadata.switchaai+idp.xml
              # metadata-uri: https://dev-15393397.okta.com/app/exkid13t0fswoJ1h75d7/sso/saml/metadata
              # metadata-uri: https://eft-dev.puzzle.ch/metadata/metadata.switchaai+idp.xml
            # metadata-uri: https://eft-dev.puzzle.ch/metadata/metadata.aaitest+idp.xml
            singlelogout:
              url: https://edview.unilu.ch/Shibboleth.sso/Logout
              response-url: https://edview.unilu.ch/

logging:
  level:
    root: info
    ch.puzzle.eft: info
    org.springframework.security: info
