server:
  forward-headers-strategy: framework
  unauthorized.urls: "/error /styles/** /javascript/** /images/** /fonts/** /favicon.ico"
  error.path: redirect:/error
  servlet:
    session:
      cookie:
        same-site: strict

spring:
  application:
    name: exam-feedback-tool
    version: @project.version@