server:
  address: edview-test.unilu.ch

spring:
  security:
    saml2:
      relyingparty:
        registration:
          okta:
            assertingparty:
              entity-id: https://edview-test.unilu.ch/idp/shibboleth
              singlesignon:
                url: https://edview-test.unilu.ch/Shibboleth.sso/Login
                binding: POST
                sign-request: false
              # metadata-uri: classpath:metadata.aaitest+idp.xml
              # metadata-uri: classpath:testxml.xml
              # metadata-uri: classpath:metadata.aaitest+idp.xml
              # metadata-uri: classpath:metadata.switchaai+idp.xml
              # metadata-uri: https://dev-15393397.okta.com/app/exkid13t0fswoJ1h75d7/sso/saml/metadata
              # metadata-uri: https://eft-dev.puzzle.ch/metadata/metadata.switchaai+idp.xml
            # metadata-uri: https://eft-dev.puzzle.ch/metadata/metadata.aaitest+idp.xml
            singlelogout:
              url: https://edview-test.unilu.ch/Shibboleth.sso/Logout
              binding: POST
              response-url: https://edview-test.unilu.ch/
#            signing:
#              credentials:
#                - private-key-location: classpath:certs/unilu-sp-pk.pem
#                  certificate-location: classpath:certs/unilu-sp.crt
