server:
  address: edview.unilu.ch
  port: 8443
  ssl:
    key-store-type: ${KS_TYPE:PKCS12}
    key-store: /${SEC_LOCATION:secrets}/httpd.keystore.p12
    key-store-password: ${KS_PW}
    key-alias: ${KEY_ALIAS:unilu-eft}
    client-auth: want
  ajp:
    protocol: https
    port: 8448
    packet.size: 65536

logging.level:
  root: info
  ch.puzzle.eft: info
  org.springframework.security: info
  org.apache: info
