server:
  address: edview.unilu.ch
  port: 8443
  ssl:
    key-store-type: ${KS_TYPE}
    key-store: /secrets/${KS_NAME}
    key-store-password: ${KS_PW}
    key-alias: ${KEY_ALIAS}
    client-auth: want
  ajp:
    protocol: https
    port: 8448
    packet.size: 65536

logging.level:
  root: info
  ch.puzzle.eft: info
  org.springframework.security: info
  org.apache: info
