server:
  address: edview-test.unilu.ch
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:certs/test/httpd.test.keystore.p12
    key-store-password: uni-lu-eft-test-2024
    key-alias: unilu-eft-test
    client-auth: want
  ajp:
    protocol: https
    port: 8448
    packet.size: 65536

# for test client only
client.ssl:
  trust-store: classpath:certs/test/httpd.test.keystore.p12
  trust-store-password: uni-lu-eft-test-2024

logging.level:
  root: info
  ch.puzzle.eft: debug
  org.springframework.security: info
  org.apache: info
