name: 'Sonarqube deployment'

on:
  push:
    branches:
      - main
      - feature/20-sonar-cube # To be removed

jobs:
  build:
    name: Build # Comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Build and analyze
        run: mvn clean verify sonar:sonar -e -Dsonar.login=${{ secrets.SONAR_TOKEN }}
