name: 'Tests'

on: [ push ]
jobs:
  Tests:
    runs-on: ubuntu-24.04
    env:
      TZ: 'Europe/Zurich'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'oracle'

      - name: Setup rootless docker
        run: |
          whoami
          id
          sudo systemctl disable --now docker.service docker.socket
          sudo apt-get update
          sudo apt-get install -y docker-ce-rootless-extras
          dockerd-rootless-setuptool.sh install

      - name: Use Maven to run unittest, integration tests and check coverage
        run: mvn clean verify
