name: ZAP

on: [push]

permissions:
  contents: read

jobs:
  test-dast:
    name: DAST test with ZAP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "oracle"
      - name: Clean install
        run: ./mvnw --no-transfer-progress clean install -DskipTests -Ddependency-check.skip -Dcyclonedx.skip=true -Dexec.skip
      - name: Start application
        run: SERVER_SERVLE_SESSION_COOOKIE_DOMAIN=http://localhost:8080 ./mvnw spring-boot:run &
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          allow_issue_writing: false
          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
          target: "http://localhost:8080"
          rules_file_name: zap/rules.conf
          fail_action: true
          cmd_options: '-z "-configFile /zap/wrk/zap/options.conf" -a'