  name: 'Tests'

  on: [push]
  jobs:
    backend-tests:
      runs-on: ubuntu-24.04
      env:
        TZ: 'Europe/Zurich'
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            java-version: 21
            distribution: 'adopt'

        - name: Use Maven to run unittest, integration tests and check coverage
          run: mvn clean verify
