name: 'Tests'

on: [ push ]
jobs:
  Tests:
    runs-on: ubuntu-24.04
    env:
      TZ: 'Europe/Zurich'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'oracle'
      - name: Setup rootless docker
        run: |
          filename=$(echo $HOME/bin/rootlesskit | sed -e s@^/@@ -e s@/@.@g)
          cat <<EOF > ~/${filename}
          abi <abi/4.0>,
          include <tunables/global>
          
          "$HOME/bin/rootlesskit" flags=(unconfined) {
            userns,
        
            include if exists <local/${filename}>
          }
          EOF
          
          sudo mv ~/${filename} /etc/apparmor.d/${filename}
          
          sudo systemctl disable --now docker.service docker.socket
          sudo rm /var/run/docker.sock
          curl -fsSL https://get.docker.com/rootless | sh
          docker context use rootless
          systemctl --user start docker

      - name: Use Maven to run unittest, integration tests and check coverage
        run: mvn clean verify
