name: 'Validate Formatting'

on: [push]
jobs:
  validate-formatting:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
      - name: Validate that the code is formatted correctly
        run: mvn spotlify:check